version: '3.8'

services:
  cuisineo_back:
    image: cuisineo_back
    container_name: cuisineo_back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    volumes:
      - .:/app
    depends_on:
      - cuisineo_mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.29.0.2:3306/cuisineo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sa
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

  cuisineo_mysql:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_DATABASE: cuisineo
      MYSQL_USER: idayat
      MYSQL_PASSWORD: sa
#      LC_MESSAGES: fr_FR.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

volumes:
  mysql_data:
